name: Score System to Heroku CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
#set environment variables 
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
  HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
  DBCONNECTION: ${{ secrets.DBCONNECTION }}
  
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Build and deploy the Docker image
      run: |
          export DATABASE_URL=${{ env.DBCONNECTION }}
          docker login --username=_ --password=${{ env.HEROKU_API_KEY }} registry.heroku.com
          docker build --build-arg DBCONNECTION_ARG="$DATABASE_URL" -t ${{ env.APP_NAME }} /score_system/score_system/
          docker tag ${{ env.APP_NAME }} registry.heroku.com/${{ env.APP_NAME }}/web
          docker push registry.heroku.com/${{ env.APP_NAME }}/web
          heroku container:release web -a ${{ env.APP_NAME }}

    
# jobs:
#   build:
#     runs-on: ubuntu-18.04
#     steps:
#     # Check-out the repository
#     - name: Checkout
#       uses: actions/checkout@v2
      

# ### ⬇ IMPORTANT PART ⬇ ###

#     - name: Build, Push and Release a Docker container to Heroku. # Your custom step name
#       uses: gonuit/heroku-docker-deploy@v1.3.3 # GitHub action name (leave it as it is).
   
#       with:
#         # Below you must provide variables for your Heroku app.

#         # The email address associated with your Heroku account.
#         # If you don't want to use repository secrets (which is recommended) you can do:
#         # email: my.email@example.com
#         email: ${{ secrets.HEROKU_EMAIL }}

#         # Heroku API key associated with provided user's email.
#         # Api Key is available under your Heroku account settings.
#         heroku_api_key: ${{ secrets.HEROKU_API_KEY }}

#         # Name of the heroku application to which the build is to be sent.
#         heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}

#         # (Optional, default: "./")
#         # Dockerfile directory.
#         # For example, if you have a Dockerfile in the root of your project, leave it as follows:
#         dockerfile_directory: score_system/

#         # (Optional, default: "Dockerfile")
#         # Dockerfile name.
#         dockerfile_name: Dockerfile
        
#         # (Optional, default: "")
#         # Additional options of docker build command.
#         docker_options: "--no-cache"

#         # (Optional, default: "web")
#         # Select the process type for which you want the docker container to be uploaded.
#         # By default, this argument is set to "web".
#         # For more information look at https://devcenter.heroku.com/articles/process-model
#         process_type: web
                  
# ### ⬆ IMPORTANT PART ⬆ ###
